Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 17, in <module>
    from GUI import main
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 5, in <module>
    import globals
ModuleNotFoundError: No module named 'globals'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 9, in <module>
    import globals
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\globals.py", line 4, in <module>
    from GUI import main
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 7, in <module>
    class MainGui(wx.Frame):
NameError: name 'wx' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 21, in <module>
    main.window.Show()
AttributeError: module 'GUI.main' has no attribute 'window'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 9, in <module>
    import globals
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\globals.py", line 4, in <module>
    from GUI import main
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 37, in <module>
    window=MainGui(application.name+" "+application.version)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 10, in __init__
    wx.Frame.__init__(self, None, title=title,size=(800,600))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 9, in <module>
    import globals
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\globals.py", line 4, in <module>
    from GUI import main
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 37, in <module>
    window=MainGui(application.name+" "+application.version)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 10, in __init__
    wx.Frame.__init__(self, None, title=title,size=(800,600))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 28, in <module>
    sound.play(urls[0])
AttributeError: module 'sound' has no attribute 'play'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 55, in play_url
    player = stream.URLStream(url)
  File "C:\python39\lib\site-packages\sound_lib\stream.py", line 128, in __init__
    handle = bass_call(
  File "C:\python39\lib\site-packages\sound_lib\main.py", line 58, in bass_call
    res = function(*args)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 28, in <module>
    sound.play_url(urls[0])
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 60, in play_url
    speak.speak("Error while playing "+url)
TypeError: can only concatenate str (not "dict") to str
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 28, in <module>
    a=urls[0]['func']['url'](urls['url'])
TypeError: 'function' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 36, in <module>
    utils.alert("No URL given.","Error")
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\utils.py", line 2, in alert
    dlg = wx.MessageDialog(parent, message, caption, wx.OK)
NameError: name 'wx' is not defined
WARNING: Falling back on generic information extractor.
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 30, in <module>
    a=urls[0]['func'](urls[0]['url'])
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 22, in ydl_url
    return info['formats'][-1]['url']
KeyError: 'formats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 33, in <module>
    utils.alert("Error while playing "+a['url']+"","Error")
NameError: name 'a' is not defined
WARNING: Falling back on generic information extractor.
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 30, in <module>
    a=urls[0]['func'](urls[0]['url'])
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 22, in ydl_url
    return info['formats'][-1]['url']
KeyError: 'formats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 33, in <module>
    utils.alert("Error while playing "+a,"Error")
NameError: name 'a' is not defined
ERROR: This live event will begin in 6 hours.
Traceback (most recent call last):
  File "C:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: This live event will begin in 6 hours.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 30, in <module>
    a=urls[0]['func'](urls[0]['url'])
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 21, in ydl_url
    info = ydl.extract_info(url, download=False, process=False)
  File "C:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This live event will begin in 6 hours.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\QPlay.pyw", line 33, in <module>
    utils.alert("Error while playing "+a,"Error")
NameError: name 'a' is not defined
ERROR: This live event will begin in 6 hours.
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 51, in OnVoldown
    if sound.player!=None:
NameError: name 'sound' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 51, in OnVoldown
    if sound.player!=None:
NameError: name 'sound' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 51, in OnVoldown
    if sound.player!=None:
NameError: name 'sound' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 51, in OnVoldown
    if sound.player!=None:
NameError: name 'sound' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 51, in OnVoldown
    if sound.player!=None:
NameError: name 'sound' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 65, in OnPlaypause
    sound.playpause()
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 73, in playpause
    if player.is_playing() == True:
TypeError: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 65, in OnPlaypause
    sound.playpause()
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 73, in playpause
    if player.is_playing() == True:
TypeError: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 65, in OnPlaypause
    sound.playpause()
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 73, in playpause
    if player.is_playing() == True:
TypeError: 'bool' object is not callable
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 67, in seek
    pos=player.get_time()
AttributeError: 'URLStream' object has no attribute 'get_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=self.player.set_time(player.seconds_to_bytes(pos))
NameError: name 'self' is not defined
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 71, in OnSeekforward
    sound.seek(5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
Traceback (most recent call last):
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\GUI\main.py", line 68, in OnSeekback
    sound.seek(-5)
  File "C:\Users\Melody\Dropbox\projects\python\py3\QPlay\sound.py", line 69, in seek
    pos=player.set_time(player.seconds_to_bytes(pos))
AttributeError: 'URLStream' object has no attribute 'set_time'
